---
- name: Install nginx web server
  apt:
    name=nginx
    state=latest
    update_cache=true

- name: Setup nginx conf
  template:
    src=default.j2
    dest=/etc/nginx/sites-available/default
  notify: restart nginx

